// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/business/v1/business.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReplayRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReplayRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplayRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReplayRequestMultiError, or
// nil if none found.
func (m *ReplayRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplayRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetReviewID() <= 0 {
		err := ReplayRequestValidationError{
			field:  "ReviewID",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetStoreID() <= 0 {
		err := ReplayRequestValidationError{
			field:  "StoreID",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetContent()); l < 2 || l > 200 {
		err := ReplayRequestValidationError{
			field:  "Content",
			reason: "value length must be between 2 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PicInfo

	// no validation rules for VideoInfo

	if len(errors) > 0 {
		return ReplayRequestMultiError(errors)
	}

	return nil
}

// ReplayRequestMultiError is an error wrapping multiple validation errors
// returned by ReplayRequest.ValidateAll() if the designated constraints
// aren't met.
type ReplayRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplayRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplayRequestMultiError) AllErrors() []error { return m }

// ReplayRequestValidationError is the validation error returned by
// ReplayRequest.Validate if the designated constraints aren't met.
type ReplayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplayRequestValidationError) ErrorName() string { return "ReplayRequestValidationError" }

// Error satisfies the builtin error interface
func (e ReplayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplayRequestValidationError{}

// Validate checks the field values on ReplayResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReplayResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplayResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReplayResponseMultiError,
// or nil if none found.
func (m *ReplayResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplayResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplyID

	if len(errors) > 0 {
		return ReplayResponseMultiError(errors)
	}

	return nil
}

// ReplayResponseMultiError is an error wrapping multiple validation errors
// returned by ReplayResponse.ValidateAll() if the designated constraints
// aren't met.
type ReplayResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplayResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplayResponseMultiError) AllErrors() []error { return m }

// ReplayResponseValidationError is the validation error returned by
// ReplayResponse.Validate if the designated constraints aren't met.
type ReplayResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplayResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplayResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplayResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplayResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplayResponseValidationError) ErrorName() string { return "ReplayResponseValidationError" }

// Error satisfies the builtin error interface
func (e ReplayResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplayResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplayResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplayResponseValidationError{}
